Feature addition Notifications
KY-Solutions/Brandify pull request #24
Opened 2024-11-28 13:39 UTC by youssef456

- User and Broadcast Notifications: The branch includes functionality to manage both user-specific notifications and broadcast notifications.
- Notification Types: Notifications can either be targeted to a specific user (via userId) or broadcast to all users (via the broad field).
- CRUD Operations: Provides full support for creating, reading, updating (mark as read), and deleting notifications.
- Sorting: Notifications are fetched and displayed sorted by their creation date (most recent first).
- Admin Control: Admin users can send notifications to all users, while regular users can fetch and manage their own notifications.
- Validation and Error Handling: Ensures correct notification data is provided, with error messages for validation issues.

2024-11-29 14:34 UTC, karim029 requested changes

2024-11-29 14:34 UTC, karim029 commented on Backend/features/Notifications/controllers/notficationController.js
> +    const userId = req.params.userId; // Assuming the userId is passed as a parameter
should be 
```js
const userId = req.userId;
```

2024-11-29 14:34 UTC, karim029 commented on Backend/features/Notifications/routes/notificationRoutes.js
> +router.get('/:userId', authMiddleware, roleMiddleware(['user', 'admin']), asyncHandler(notificationController.fetchNotifications));
remove 
```js
:userId
```
since you are using the autMiddleware

2024-11-29 14:34 UTC, karim029 commented on Backend/features/Notifications/routes/notificationRoutes.js
> +router.put('/:id', authMiddleware, roleMiddleware(['user', 'admin']), asyncHandler(notificationController.markAsRead)); // Mark notification as read
remove 
```js
:id
```
since you are using Authmiddleware and get the userId from the req.userId

2024-11-29 14:34 UTC, karim029 commented on Backend/features/Notifications/controllers/notficationController.js
> +  const { id } = req.params;
replace it with
```js
const userId = req.userId;
```

2024-12-01 13:30 UTC, merged

2024-12-01 21:02 UTC, youssef456 commented on Backend/features/Notifications/routes/notificationRoutes.js
> +router.put('/:id', authMiddleware, roleMiddleware(['user', 'admin']), asyncHandler(notificationController.markAsRead)); // Mark notification as read
This is the notification id not the user id

2024-12-01 21:02 UTC, youssef456 commented on Backend/features/Notifications/controllers/notficationController.js
> +  const { id } = req.params;
This is also user for the notification id not the user id